
spring:
  application:
    name: retail-product-catalog

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8090

fuzzy:
  search:
    threshold: 5

apis:
  logging:
    enabled: true
